version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rusty_anchor_db
    restart: always
    environment:
      POSTGRES_DB: rusty_anchor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
